import { Building2, CalendarRange, CircleDollarSign, GraduationCap, Landmark, MapPin, Plus, Save, Trash2, UsersRound } from "lucide-react";
import { Field, FieldArray, Form, Formik } from "formik";
import type { College, MasterConfiguration, University } from "../types";
import { Button, Card, Input } from "./ui";

interface CourseDraft { course: string; batch: string; admissionCenter: string; courseStart: string; courseEnd: string; fee: number; }
interface CollegeDraft { name: string; city: string; contactName: string; courses: CourseDraft[]; }
export interface UniversitySetupValues { name: string; city: string; adminName: string; adminEmail: string; password: string; colleges: CollegeDraft[]; }
interface SettingsProps { universities: University[]; colleges: College[]; configurations: MasterConfiguration[]; onSaveUniversitySetup: (values: UniversitySetupValues) => void; }

const emptyCourse = (): CourseDraft => ({ course: "", batch: "", admissionCenter: "", courseStart: "", courseEnd: "", fee: 0 });
const emptyCollege = (): CollegeDraft => ({ name: "", city: "", contactName: "", courses: [emptyCourse()] });
const initialValues: UniversitySetupValues = { name: "", city: "", adminName: "", adminEmail: "", password: "", colleges: [emptyCollege()] };

export function Settings({ universities, colleges, configurations, onSaveUniversitySetup }: SettingsProps) {
  return <div className="page-content settings-page">
    <div className="master-flow"><span className="flow-step active"><b>1</b> University</span><i/><span className="flow-step active"><b>2</b> Colleges</span><i/><span className="flow-step active"><b>3</b> Courses & batches</span></div>
    <p className="flow-caption">Create a university once, add as many colleges as needed, then assign multiple courses and internship batches to every college.</p>
    <div className="settings-overview"><Card><Building2/><span><b>{universities.length}</b><small>Universities</small></span></Card><Card><GraduationCap/><span><b>{colleges.length}</b><small>Colleges</small></span></Card><Card><CalendarRange/><span><b>{configurations.length}</b><small>Courses configured</small></span></Card><Card><MapPin/><span><b>{new Set(configurations.map(item => item.admissionCenter)).size}</b><small>Admission centers</small></span></Card></div>
    <Formik initialValues={initialValues} onSubmit={(values, { resetForm }) => { onSaveUniversitySetup(values); resetForm(); }}>
      {({ values }) => <Form className="university-setup">
        <Card className="settings-card university-card"><div className="card-head"><div><h2>University details</h2><p>This creates the parent record and university admin access.</p></div><Building2 size={19}/></div><div className="settings-form">
          <label>University name<Field as={Input} name="name" placeholder="e.g. Delhi University" required /></label><label>City / state<Field as={Input} name="city" placeholder="e.g. New Delhi" required /></label><label>Admin name<Field as={Input} name="adminName" placeholder="Full name" required /></label><label>Admin email<Field as={Input} type="email" name="adminEmail" placeholder="admin@university.edu" required /></label><label className="full-field">Temporary password<Field as={Input} type="password" name="password" placeholder="Set initial password" required /></label>
        </div></Card>
        <FieldArray name="colleges">{({ push: addCollege, remove: removeCollege }) => <div className="nested-forms"><div className="nested-heading"><div><h2>Colleges and courses</h2><p>Add all colleges for this university and attach one or more courses to each one.</p></div><Button type="button" className="button-outline" onClick={() => addCollege(emptyCollege())}><Plus size={16}/> Add college</Button></div>{values.colleges.map((college, collegeIndex) => <Card className="college-builder" key={`college-${collegeIndex}`}><div className="card-head"><div><span className="eyebrow">COLLEGE {collegeIndex + 1}</span><h2>{college.name || "New college"}</h2></div>{values.colleges.length > 1 && <button type="button" className="text-danger" onClick={() => removeCollege(collegeIndex)}><Trash2 size={16}/> Remove</button>}</div><div className="settings-form"><label>College name<Field as={Input} name={`colleges.${collegeIndex}.name`} placeholder="e.g. Hansraj College" required /></label><label>City / state<Field as={Input} name={`colleges.${collegeIndex}.city`} placeholder="e.g. New Delhi" required /></label><label className="full-field">College coordinator<Field as={Input} name={`colleges.${collegeIndex}.contactName`} placeholder="Full name" required /></label></div><FieldArray name={`colleges.${collegeIndex}.courses`}>{({ push: addCourse, remove: removeCourse }) => <div className="course-builder"><div className="course-heading"><div><CircleDollarSign size={17}/><b>Courses and internship batches</b></div><Button type="button" className="button-outline small-action" onClick={() => addCourse(emptyCourse())}><Plus size={15}/> Add course</Button></div>{college.courses.map((course, courseIndex) => <div className="course-row" key={`course-${courseIndex}`}><span className="course-number">{courseIndex + 1}</span><div className="course-fields"><label>Course<Field as={Input} name={`colleges.${collegeIndex}.courses.${courseIndex}.course`} placeholder="Web Development" required /></label><label>Internship batch<Field as={Input} name={`colleges.${collegeIndex}.courses.${courseIndex}.batch`} placeholder="Summer 2024" required /></label><label>Admission center<Field as={Input} name={`colleges.${collegeIndex}.courses.${courseIndex}.admissionCenter`} placeholder="Center name" required /></label><label>Course start<Field as={Input} type="date" name={`colleges.${collegeIndex}.courses.${courseIndex}.courseStart`} required /></label><label>College course end<Field as={Input} type="date" name={`colleges.${collegeIndex}.courses.${courseIndex}.courseEnd`} required /></label><label>Course fee (INR)<Field as={Input} type="number" min="0" name={`colleges.${collegeIndex}.courses.${courseIndex}.fee`} required /></label></div>{college.courses.length > 1 && <button type="button" className="icon-button remove-course" aria-label="Remove course" onClick={() => removeCourse(courseIndex)}><Trash2 size={16}/></button>}</div>)}</div>}</FieldArray></Card>)}</div>}</FieldArray>
        <div className="setup-actions"><span><Landmark size={17}/> {values.colleges.length} college{values.colleges.length === 1 ? "" : "s"} and {values.colleges.reduce((count, college) => count + college.courses.length, 0)} course{values.colleges.reduce((count, college) => count + college.courses.length, 0) === 1 ? "" : "s"} ready to save</span><Button type="submit"><Save size={16}/> Save university structure</Button></div>
      </Form>}
    </Formik>
    <div className="settings-data-grid"><Card className="master-list"><div className="card-head"><div><h2>University & college directory</h2><p>Current organisation structure</p></div><UsersRound size={19}/></div>{universities.map(university => <div className="master-row" key={university.id}><span className="master-icon"><Building2 size={17}/></span><div><b>{university.name}</b><small>{university.city} · {university.adminEmail}</small></div><div className="master-meta"><b>{colleges.filter(college => college.universityId === university.id).length} colleges</b><small>{university.adminName}</small></div></div>)}</Card><Card className="master-list"><div className="card-head"><div><h2>Course configurations</h2><p>College-specific fees and timelines</p></div><GraduationCap size={19}/></div>{configurations.map(config => <div className="master-row" key={`${config.course}-${config.collegeId}-${config.batch}`}><span className="master-icon"><GraduationCap size={17}/></span><div><b>{config.course} · {config.batch}</b><small>{config.college} · {config.admissionCenter}</small></div><div className="master-meta"><b>₹{config.fee.toLocaleString("en-IN")}</b><small>{config.courseStart} to {config.courseEnd}</small></div></div>)}</Card></div>
  </div>;
}
