import { useEffect, useState } from "react";
import { Dashboard } from "./components/dashboard";
import { Sidebar } from "./components/sidebar";
import { Header } from "./components/header";
import { Attendance } from "./components/attendance";
import { Payments } from "./components/payments";
import { Students } from "./components/students";
import { Internships } from "./components/internships";
import { Courses } from "./components/courses";
import { Settings, type UniversitySetupValues } from "./components/settings";
import { StudentForm } from "./components/student-form";
import { SignIn, UniversitySelect, type UserRole } from "./components/auth";
import { toast, ToastViewport } from "./components/toast";
import { storage } from "./lib/storage";
import type { College, InternshipTopic, MasterConfiguration, Student, Theme, University } from "./types";

const headings: Record<string, [string,string]> = { dashboard: ["Good morning, Priya", "Here's what's happening across your internship programs."], students: ["Students", "Manage registrations, learner profiles, and assignments."], attendance: ["Attendance", "Record and review daily learner attendance."], payments: ["Payments", "Verify transactions and manage learner payments."], internships: ["Internships", "Monitor milestones from registration to certification."], courses: ["Courses", "Manage internship topics, courses, fees and student resources."], settings: ["University", "Manage university, college, course, and batch master data."] };
type AppStage = "sign-in" | "university-select" | "panel";
export default function App() { const [stage,setStage]=useState<AppStage>("sign-in"); const [role,setRole]=useState<UserRole>("admin"); const [view,setView]=useState("dashboard"); const [theme,setTheme]=useState<Theme>(() => localStorage.getItem("theme") as Theme || "light"); const [students,setStudents]=useState<Student[]>([]); const [payments,setPayments]=useState(storage.payments()); const [universities,setUniversities]=useState<University[]>([]); const [selectedUniversityId,setSelectedUniversityId]=useState(""); const [colleges,setColleges]=useState<College[]>([]); const [configurations,setConfigurations]=useState<MasterConfiguration[]>([]); const [topics,setTopics]=useState<InternshipTopic[]>([]); const [editing,setEditing]=useState<Student | null>(null); const [present,setPresent]=useState(new Set<string>()); const [sidebarCollapsed,setSidebarCollapsed]=useState(false);
useEffect(()=>{storage.initialize();setStudents(storage.students());const savedUniversities=storage.universities();setUniversities(savedUniversities);setSelectedUniversityId(savedUniversities[0]?.id ?? "");setColleges(storage.colleges());setConfigurations(storage.masterConfigurations());setTopics(storage.internshipTopics());},[]); useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("theme",theme)},[theme]); const current=headings[view] || headings.dashboard; const selectedUniversity=universities.find(university=>university.id===selectedUniversityId) ?? universities[0];
const updateStudent=(s:Student)=>{const next=students.map(item=>item.id===s.id?s:item);setStudents(next);storage.saveStudents(next);toast.success("Student details saved locally.")}; const markPaid=(id:string)=>{const next=payments.map(p=>p.id===id?{...p,status:"Paid" as const}:p);setPayments(next);storage.savePayments(next);toast.success("Payment status updated to paid.")}; const saveUniversitySetup=(values:UniversitySetupValues)=>{const universityId=`UNI-${Date.now()}`;const university:University={id:universityId,name:values.name,city:values.city,adminName:values.adminName,adminEmail:values.adminEmail};const nextUniversities=[...universities,university];const newColleges=values.colleges.map((college,index):College=>({id:`COL-${Date.now()}-${index}`,universityId,name:college.name,city:college.city,contactName:college.contactName}));const nextColleges=[...colleges,...newColleges];const newConfigurations=values.colleges.flatMap((college,collegeIndex)=>college.courses.map((course,courseIndex):MasterConfiguration=>({universityId,collegeId:newColleges[collegeIndex].id,college:college.name,course:course.course,batch:course.batch,admissionCenter:course.admissionCenter,courseStart:course.courseStart,courseEnd:course.courseEnd,fee:Number(course.fee)})));const nextConfigurations=[...configurations,...newConfigurations];setUniversities(nextUniversities);setColleges(nextColleges);setConfigurations(nextConfigurations);storage.saveUniversities(nextUniversities);storage.saveColleges(nextColleges);storage.saveMasterConfigurations(nextConfigurations);toast.success("University structure saved locally.")}; const toggle=(id:string)=>setPresent(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});
if(stage==="sign-in")return <><SignIn theme={theme} setTheme={setTheme} onAuthenticated={(nextRole)=>{setRole(nextRole);setStage(nextRole==="admin"?"university-select":"panel")}}/><ToastViewport/></>;
if(stage==="university-select")return <><UniversitySelect universities={universities} onSelect={(university)=>{setSelectedUniversityId(university.id);setStage("panel")}} onBack={()=>setStage("sign-in")}/><ToastViewport/></>;
if(!selectedUniversity)return null;
return <><div className={`app-shell ${sidebarCollapsed ? "sidebar-is-collapsed" : ""}`}><Sidebar active={view} onChange={setView} collapsed={sidebarCollapsed} universities={universities} university={selectedUniversity} onUniversityChange={setSelectedUniversityId} onLogout={() => setStage("sign-in")}/><main className="main"><Header theme={theme} setTheme={setTheme} title={current[0]} description={role==="admin"?`${current[1]} Managing ${selectedUniversity.name}.`:current[1]} sidebarCollapsed={sidebarCollapsed} onSidebarToggle={() => setSidebarCollapsed(value => !value)}/>{view === "dashboard" && <Dashboard students={students} payments={payments} onView={setView}/>} {view === "students" && <Students students={students} onEdit={setEditing}/>} {view === "attendance" && <Attendance students={students} present={present} onToggle={toggle}/>} {view === "payments" && <Payments payments={payments} onMarkPaid={markPaid}/>} {view === "internships" && <Internships students={students}/>} {view === "courses" && <Courses topics={topics} onSave={(nextTopics) => { setTopics(nextTopics); storage.saveInternshipTopics(nextTopics); toast.success("Course catalogue saved locally."); }}/>} {view === "settings" && <Settings universities={universities} colleges={colleges} configurations={configurations} onSaveUniversitySetup={saveUniversitySetup}/>}</main>{editing && <StudentForm student={editing} onClose={()=>setEditing(null)} onSave={updateStudent}/>}</div><ToastViewport/></>; }
